### ISSUE TITLE
Not considering dpi scaling results in wrong positions of start and end points on Linux

### ISSUE THREAD

**Issue by adwinwhite** [ianzhao05/textshot#9]
Here is an example.
The positions captured by the program:
```bash
start:1227,695
end:1272,715
```
Their real positions:
```bash
start:3681,2085
end:3816,2145
```

Thus `pyscreenshot` grabs the wrong image.

My scale factor:
```bash
GDK_DPI_SCALE=0.333
GDK_SCALE=3
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_SCREEN_SCALE_FACTORS=eDP1=3;DP1=3;DP2=3;HDMI1=3;HDMI2=3;VIRTUAL1=3;
```

**Comment by ianzhao05** [comment]
Hi, I pushed some small changes that hopefully fix the issue in PR #10. It works well in my testing, but may you please confirm that this resolves the issue?

**Comment by adwinwhite** [comment]
Unfortunately it doesn't resolve the issue. The code you changed seems to be irrelevant to hidpi scale on Linux. I'll make a pull request which should work for a single hidpi monitor.

**Comment by ianzhao05** [comment]
Ok, thanks. I thought that using global coordinates might bypass the DPI scale of the application, but I guess not. I can't test, but https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt, in particular `Qt::AA_DisableHighDpiScaling`, seems interesting.

**Comment by adwinwhite** [comment]
Well, I can help test if `Qt::AA_DisableHighDpiScaling` works.

**Comment by ianzhao05** [comment]
I added a commit to my PR #10 that adds that attribute. Can you check if it works? Thank you for your help.

**Comment by adwinwhite** [comment]
works like a charm!

**Comment by ianzhao05** [comment]
Great! Thanks for testing.
